version = 1

test_patterns = ["test/**"]

exclude_patterns = [
    ".github/**",
    "dist/**",
    "docs/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "commonjs"
  environment = [
    "nodejs",
    "jasmine"
  ]
  dialect = "typescript"